import React, { useState, useEffect, useRef } from 'react';
import './App.css';
import { getFragmentById, getCycleInfo, getCharacterFromId } from './fragments';
import { isFeatureUnlocked, UI_FEATURES } from './discoveryState';
import ConstellationView from './ConstellationView';
import EchoBird from './EchoBird';
import LibraryView from './LibraryView';
import CassandraChat from './CassandraChat';
import CassandraFeed from './CassandraFeed';
import { useFragmentNavigation } from './hooks/useFragmentNavigation';
import { sendAnalyticsEvent } from './analytics.js';

const PREVIEW_EXCERPT_LENGTH = 150;

function App() {
  const nav = useFragmentNavigation();

  const contentRef = useRef(null);
  const fragmentEnteredAt = useRef(null);
  const prevFragmentId = useRef(null);
  const chatOpenedAt = useRef(null);
  const [voiceMap, setVoiceMap] = useState({});
  const [showConstellation, setShowConstellation] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [showLibrary, setShowLibrary] = useState(false);
  const [showCassandra, setShowCassandra] = useState(false);
  const [showFeed, setShowFeed] = useState(false);

  // Load voice annotations (generated by analyzeVoices.js, served from /voices.json)
  useEffect(() => {
    fetch('/voices.json')
      .then(r => r.ok ? r.json() : {})
      .then(setVoiceMap)
      .catch(() => {});
  }, []);

  // Fragment read timing
  useEffect(() => {
    const now = Date.now();
    if (prevFragmentId.current && fragmentEnteredAt.current) {
      sendAnalyticsEvent('fragment_viewed', {
        fragmentId: prevFragmentId.current,
        durationMs: now - fragmentEnteredAt.current,
      });
    }
    prevFragmentId.current = nav.currentFragment?.id || null;
    fragmentEnteredAt.current = now;
  }, [nav.currentFragment?.id]);

  // Chat open/close timing
  useEffect(() => {
    if (showCassandra) {
      chatOpenedAt.current = Date.now();
      sendAnalyticsEvent('chat_opened', {});
    } else if (chatOpenedAt.current) {
      sendAnalyticsEvent('chat_closed', { durationMs: Date.now() - chatOpenedAt.current });
      chatOpenedAt.current = null;
    }
  }, [showCassandra]);

  // Gradual text reveal at ~155 wpm.
  // Scroll toward the shadow to accelerate (organic, up to ~5×).
  // Tap/click the text to reveal instantly.
  useEffect(() => {
    if (!nav.currentFragment || !contentRef.current) return;
    const el = contentRef.current;
    el.style.setProperty('--reveal', '0%');

    const wordCount = nav.currentFragment.content.split(/\s+/).length;
    const basePctPerMs = 115 / ((wordCount / 155) * 60 * 1000);

    let currentPct = 0;
    let speedMultiplier = 1;
    let lastNow = performance.now();
    let rafId;

    const tick = (now) => {
      const delta = now - lastNow;
      lastNow = now;
      currentPct = Math.min(115, currentPct + basePctPerMs * delta * speedMultiplier);
      el.style.setProperty('--reveal', `${currentPct.toFixed(2)}%`);
      if (currentPct < 115) rafId = requestAnimationFrame(tick);
    };

    // Scroll toward the shadow → organic speed ramp.
    // Shadow viewport-y: rect.top + el.clientHeight * (currentPct / 100)
    // Boost starts 250px before shadow enters viewport, peaks at ~5× when shadow is 200px inside.
    const handleScroll = () => {
      if (currentPct >= 115) return;
      const rect = el.getBoundingClientRect();
      const shadowY = rect.top + el.clientHeight * (currentPct / 100);
      const dist = window.innerHeight - shadowY; // positive = shadow inside viewport
      if (dist > -250) {
        speedMultiplier = 1 + Math.min(4, Math.max(0, dist + 250) / 112);
      } else {
        speedMultiplier = 1;
      }
    };

    // Tap / click → instant complete
    const handleClick = (e) => {
      if (e.target.closest('a, button')) return;
      if (currentPct >= 115) return;
      cancelAnimationFrame(rafId);
      currentPct = 115;
      el.style.setProperty('--reveal', '115%');
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    el.addEventListener('click', handleClick);
    rafId = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener('scroll', handleScroll);
      el.removeEventListener('click', handleClick);
    };
  }, [nav.currentFragment?.id]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyPress = (e) => {
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === 'C') {
        e.preventDefault();
        setShowCassandra(prev => !prev);
      }
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        nav.navigateToNext();
      }
      if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        nav.navigateToPrevious();
      }
    };
    window.addEventListener('keydown', handleKeyPress);
    return () => window.removeEventListener('keydown', handleKeyPress);
  }, [nav]);

  if (!nav.currentFragment) {
    return (
      <div className="app">
        <div className="header">
          <h1>Echoes</h1>
          <p>Loading the fragments...</p>
        </div>
      </div>
    );
  }

  const cycleInfo = getCycleInfo(nav.currentFragment.id);
  const character = getCharacterFromId(nav.currentFragment.id);

  return (
    <div className="app">
      <header className="header">
        <h1>Echoes</h1>
        <p>A Non-Linear Journey Through Fragments of Thought</p>

        <div className="header-toolbar">
          {isFeatureUnlocked(UI_FEATURES.CONSTELLATION, nav.discoveryState) && (
            <button className="toolbar-btn" onClick={() => setShowConstellation(true)} title="View all fragments">
              ✦ Constellation
            </button>
          )}
          {isFeatureUnlocked(UI_FEATURES.HISTORY, nav.discoveryState) && (
            <button className="toolbar-btn" onClick={() => setShowHistory(!showHistory)} title="View reading history">
              ⟲ History ({nav.readingHistory.length})
            </button>
          )}
          {isFeatureUnlocked(UI_FEATURES.LIBRARY, nav.discoveryState) && (
            <button className="toolbar-btn library-btn" onClick={() => setShowLibrary(true)} title="The Library of Echoes — voices from the mirror">
              𓅓 Library
            </button>
          )}
          <button className="toolbar-btn feed-btn" onClick={() => setShowFeed(true)} title="Cassandra's reflections">
            ✦ Cassandra writes
          </button>
          <button className="toolbar-btn reset-btn" onClick={nav.resetJourney} title="Reset your journey to the beginning">
            ↻ Reset Journey
          </button>
        </div>

        <div className="discovery-progress">
          <span className="discovery-count">{nav.discoveryState.discoveredFragments.size} fragments discovered</span>
        </div>

      </header>

      {showHistory && nav.readingHistory.length > 0 && (
        <div className="reading-history">
          <h3>Your Path Through the Fragments</h3>
          <div className="history-list">
            {nav.readingHistory.map((fragmentId, index) => {
              const frag = getFragmentById(fragmentId);
              if (!frag) return null;
              return (
                <div
                  key={`${fragmentId}-${index}`}
                  className={`history-item ${fragmentId === nav.currentFragment.id ? 'current' : ''}`}
                  onClick={() => nav.navigateToFragment(fragmentId)}
                >
                  <span className="history-number">{index + 1}.</span>
                  <span className="history-title">{frag.title}</span>
                  <span className="history-character">{getCharacterFromId(fragmentId)}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="background-fragments">
        {nav.connectedFragments.slice(0, 5).map((fragment, index) => (
          <div
            key={fragment.id}
            className={`floating-fragment floating-fragment-${index} mood-${fragment.mood.toLowerCase().replace(/\s+/g, '-')}`}
            onMouseEnter={() => nav.setHoveredFragment(fragment)}
            onMouseLeave={() => nav.setHoveredFragment(null)}
            onClick={() => nav.navigateToFragment(fragment.id)}
            style={{
              animationDelay: `${index * 0.5}s`,
              animationDuration: `${20 + index * 8}s`,
              '--dx': `${5 + index * 6}px`,
              '--dy': `${10 + index * 8}px`,
              '--rot': `${index * 2}deg`
            }}
          >
            <div className="floating-fragment-content">
              <div className="floating-fragment-title">{fragment.title}</div>
              <div className="floating-fragment-mood-indicator" />
            </div>
          </div>
        ))}
      </div>

      <div className={`fragment-container ${nav.fadeIn ? 'fade-in' : ''}`}>
        <article className="fragment-card">
          <div className="fragment-header">
            <h2 className="fragment-title">{nav.currentFragment.title}</h2>
          </div>

          <div className="fragment-content" ref={contentRef} style={{'--reveal': '115%'}}>
            {(() => {
              const annotation = voiceMap[nav.currentFragment.id];
              if (annotation?.length) {
                return annotation.map((seg, i) =>
                  seg.voice === 'epigraph'
                    ? <blockquote key={i} className="fragment-epigraph">{seg.text}</blockquote>
                    : <span key={i} className={`voice-segment voice-${seg.voice.toLowerCase()}`}>{seg.text}</span>
                );
              }
              // Fallback: plain text with epigraph detection
              const content = nav.currentFragment.content;
              const firstNewline = content.indexOf('\n');
              const firstLine = firstNewline > -1 ? content.slice(0, firstNewline).trim() : '';
              const rest = firstNewline > -1 ? content.slice(firstNewline + 1) : content;
              const isEpigraph = /^"[^"]*"[\s\u2014\u2013—–-]+\S/.test(firstLine);
              return isEpigraph ? (
                <><blockquote className="fragment-epigraph">{firstLine}</blockquote>{rest}</>
              ) : content;
            })()}
          </div>

          <footer className="fragment-footer">
            <span className="fragment-character">{character}</span>
            <span className="cycle-label">{cycleInfo.cycle}</span>
          </footer>

          <div className="controls">
            <button className="nav-inline" onClick={() => { nav.navigateToPrevious(); sendAnalyticsEvent('navigation', { method: 'prev' }); }} disabled={!nav.hasPrevious()} title="Previous fragment">‹</button>
            <button className="drift-btn" onClick={() => { nav.navigateToRandom(); sendAnalyticsEvent('navigation', { method: 'random' }); }} title="Drift to a random fragment">✦</button>
            <button className="nav-inline" onClick={() => { nav.navigateToNext(); sendAnalyticsEvent('navigation', { method: 'next' }); }} disabled={!nav.hasNext()} title="Next fragment">›</button>
          </div>
        </article>
      </div>

      {nav.hoveredFragment && (
        <div className="hover-preview">
          <h3>{nav.hoveredFragment.title}</h3>
          <p className="hover-preview-excerpt">
            {nav.hoveredFragment.content.substring(0, PREVIEW_EXCERPT_LENGTH)}...
          </p>
        </div>
      )}

      {nav.showContemplation && nav.pendingNavigation && (
        <div className="contemplation-overlay" onClick={() => nav.setShowContemplation(false)}>
          <div className="contemplation-modal" onClick={(e) => e.stopPropagation()}>
            <div className="contemplation-content">
              <p className="contemplation-question">Before you drift...</p>
              <p className="contemplation-reflection">What draws you forward?</p>
              <p className="contemplation-hint">The next fragment awaits: <em>{nav.pendingNavigation.title}</em></p>
              <div className="contemplation-actions">
                <button className="contemplation-btn contemplation-continue" onClick={() => nav.performNavigation(nav.pendingNavigation)}>
                  Continue
                </button>
                <button className="contemplation-btn contemplation-stay" onClick={() => nav.setShowContemplation(false)}>
                  Stay Here
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {nav.unlockNotification && (
        <div className="unlock-notification">
          <div className="unlock-content">
            <div className="unlock-icon">✨</div>
            <p className="unlock-message">{nav.unlockNotification.message}</p>
            <button className="unlock-dismiss" onClick={() => nav.setUnlockNotification(null)}>✕</button>
          </div>
        </div>
      )}

      {showConstellation && (
        <ConstellationView
          currentFragmentId={nav.currentFragment.id}
          onNavigate={nav.navigateToFragment}
          onClose={() => setShowConstellation(false)}
          discoveryState={nav.discoveryState}
        />
      )}

      {showLibrary && (
        <LibraryView
          onNavigate={nav.navigateToFragment}
          onClose={() => setShowLibrary(false)}
          discoveryState={nav.discoveryState}
        />
      )}

      {showCassandra && (
        <CassandraChat
          onClose={() => setShowCassandra(false)}
          currentFragmentId={nav.currentFragment?.id}
        />
      )}

      {showFeed && (
        <CassandraFeed onClose={() => setShowFeed(false)} />
      )}

      <EchoBird
        onLibraryRequest={() => setShowLibrary(true)}
        onCassandraRequest={() => setShowCassandra(true)}
      />
    </div>
  );
}

export default App;
